### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by zemlya1unicorn** [zemlya1unicorn/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by GlobalMaxim** [comment]
My two greatest assets have been mental stability and being, like, really smart. I went from very successful businessman, to top T.V. Star.  I have a Nuclear Button, but it is a much bigger and more powerful than Kim Chen In's one, and moreover my Button works)
