### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by zemlya1unicorn** [zemlya1unicorn/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by GlobalMaxim** [comment]
https://www.facebook.com/DonaldTrump/
http://www.donaldjtrump.com/
https://www.instagram.com/realdonaldtrump/
https://twitter.com/realDonaldTrump
