### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by zemlya1unicorn** [zemlya1unicorn/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by GlobalMaxim** [comment]
**June 14 , 1946** 
Donald Trump is Born in Queens , New York .

**1959** 
Leaves for the New York Military Academy

**1966** 
Transfers to Penn's Wharton School of Business , and almost immediately begins buying properties in Philadelphia .

**October 6 , 1973** 
The U.S. Justice Department sues the Trump Organization , charging that it frequently violated the Fair Housing Act by 
discriminating against black potential

**April 9 , 1977** 
Marries Ivana Zelnickova Winklmayr

**December 31 , 1977** 
Donald John Trump Jr. is born

**October 30 , 1981** 
Ivanka Marie Trump is born

**July 1982** 
With Mayor Ed Koch , celebrates the completion of Trump Tower in Manhattan

**January 6 , 1984** 
Eric Frederic Trump is born .

**1987** 
Publishes The Art of the Deal , which spends 51 weeks on the New York Times bestseller list .

**January 1989** 
First appears on the cover of Time

**1990**
 Is removed from the Forbes 400 list

**February 1990** 
Separates from Ivana , eventually divorcing in 1992

**1991** 
Files for bankruptcy for the first time

**October 13 , 1993** 
Marla Maples gives birth to Tiffany Trump

**December 20 , 1993** 
Marries Marla

**1996** 
Buys the Miss Universe Organization

**1999** 
Divorces Marla

**March 2000** 
The Simpsons airs " Bart to the Future , " an episode in which Trump becomes president of the United States

**June 2003**
 Files suit against Native American tribe and rival developer the Eastern Pequots

**2005** 
Marries Melania Knauss

**January 8 , 2004** 
The Apprentice premieres 

**2005** 
Opens Trump University which is eventually down amid lawsuits from students and the New attorney general alleging was a scam .

**March 20 , 2006**
 Barron Trump is born

**January 6 , 2007** 
Receives star on the Hollywood Walk Fame

**October 2012** 
Offers Barack Obama $ 5 million to the charity of his choice in exchange for the president releasing his birth certificate

**2014** 
Sues Trump Entertainment Resorts to remove his name from the Trump Taj Mahal and Trump Plaza casinos , saying they were not up to his standards

**June 16 , 2015** 
Announces his bid for the U.S. presidency in a speech that included remarks about Mexican immigrants being " rapists " and drug dealers

**June 29 , 2015** 
NBC cuts business ties with Trump following his immigration remarks
