### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by zemlya1unicorn** [zemlya1unicorn/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by GlobalMaxim** [comment]
**Skills & Competences** 
- Decision Making 
- Confidence 
- Storytelling 
- Public Speaking 
- Negotiation 
- Deflection 
- Goal Setting 
- Authenticity 
- Charisma

**Achievements** 

- Star on the Hollywood Walk of Fame Received the 2015 Marine Corps - Law Enforcement Foundation's annual Leadership Award in recognition for his contributions to American military education programs . 
- New Jersey Boxing Hall of Fame ( November 2015 ) 
- Liberty Award at the Algemeiner Jewish 100 Gala ( 2015 ) in honor of his positive contributions to Israel - United States relations . 
- Statesman of the Year , The Republican Party of Sarasota ( 2012 and 2015 ) 
- Honorary Doctor of Business ( Hon . D.B. ) From Liberty University in 2012 
- 2007 Muhammad Ali Entrepreneur Award

**Books written** (most recent)

- Crippled America : How to Make America Great Again ( 2015 )
- Time to Get Tough : Making America No. 1 Again ( 2011 ) 
- Midas Touch : Why Some Entrepreneurs Get Rich — and why Most Don't ( 2011 ) 
- Think Like a Champion : An Informal Education in Business and Life ( 2009 )
- Trump Never Give Up : How I Turned My Biggest Challenges into Success ( 2008 )

**Interests** 

Golf | Cars | Miss Universe | Stock Market | Investment | Real estate | Entrepreneurship
